services:
  redis:
    image: redis:latest
    container_name: ms-redis
    hostname: redis
    restart: always
    ports:
      - '6400:6379'
  
  postgres:
    image: postgres:latest
    environment:
#      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: "exit 0"
    ports:
      - 5445:5432

  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    environment:
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: postgres
      KC_DB_PASSWORD: secret
      KC_DB_USERNAME: postgres
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/localhost.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/localhost-key.pem
    volumes:
      - ./localhost.pem:/opt/keycloak/conf/localhost.pem
      - ./localhost-key.pem:/opt/keycloak/conf/localhost-key.pem
    ports:
      - 8095:8443
      - 8094:8080
    depends_on:
      postgres:
        condition: service_healthy